# Generated by Django 3.1.1 on 2020-12-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job', models.CharField(blank=True, max_length=60)),
                ('image', models.ImageField(blank=True, upload_to='person/')),
                ('text', models.TextField()),
            ],
        ),
    ]
